# Reload config
unbind r
bind r source-file ~/.tmux.conf

# Mouse
set -g mouse on

# Pane navigation (vim style)
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Terminal colors
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Vi mode
set-window-option -g mode-keys vi

# Status bar
set-option -g status-justify left
set-option -g status-fg cyan
set-option -g status-bg black

# Pane / window styling
set -g pane-active-border-style fg=colour166,bg=default
set -g window-style fg=colour10,bg=default
set -g window-active-style fg=colour12,bg=default

# History
set-option -g history-limit 64096

# Faster escape
set -sg escape-time 10

# Terminal title
set -g set-titles on
set -g set-titles-string "#T"

# Load styling files
source ~/.config/tmux/theme.conf
source ~/.config/tmux/statusline.conf
source ~/.config/tmux/utility.conf

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'

# TPM must be last
run '~/.tmux/plugins/tpm/tpm'
