# vim: ft=tmux

set -g mode-style "fg=#ebdbb2,bg=#3c3836"

set -g message-style "fg=#ebdbb2,bg=#3c3836"
set -g message-command-style "fg=#ebdbb2,bg=#3c3836"

set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#fabd2f"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#a89984,bg=#282828"

set -g status-bg "#282828"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#282828,bg=#fabd2f,bold] #S:#I.#P #[fg=#fabd2f,bg=#3c3836]#[fg=#ebdbb2,bg=#3c3836,bold] #(whoami) #[fg=#3c3836,bg=#282828]"

set -g status-right "#[fg=#a89984,bg=#282828]#[fg=#ebdbb2,bg=#504945] #[fg=#ebdbb2,bg=#504945]#[fg=#282828,bg=#a89984,bold] #h "

setw -g window-status-activity-style "underscore,fg=#a89984,bg=#282828"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#a89984,bg=#282828"

setw -g window-status-format '#[fg=#002b36,bg=#002b36]#[default] #I  #W #[fg=#002b36,bg=#002b36,nobold,nounderscore,noitalics]'

setw -g window-status-current-format '#[fg=#002b36,bg=#eee8d5]#[fg=#b58900,bg=#eee8d5] #I #[fg=#eee8d5,bg=#b58900] #W #[fg=#b58900,bg=#002b36,nobold]'
